.github/workflows/deploy-stubs.yml, .github/workflows/run-checks.yml
Sam build and validation will fail in github actions as we have renames the template files. 
As we have multiple files we will have multiple actions. As a temporary fix the current actions will point to the `IPV template` file and will raise another PR to separate out the workflows to the specific template files and restructure.
=> ATO-NONE: Point to IPV template files

package-lock.json, package.json, src/main/ipv-stub/ipv-authorize.ts, src/main/logger.ts
Adding a very basic logger. This can be expanded to include `pino-http` and have more settings to customise it (see auth-frontend for example)
=> BAU: Add pino logger

package.json
Add auth and ipv individual build/start scripts for testing so that it doesn't require both to be running.
=> BAU: Separate scripts into Auth and IPV for simplified testing

package-lock.json, package.json
A previous change removed a transitive dependency on ts-node, which meant Jest could no longer read it's ts config tile
=> BAU: fix tests

ipv-stub-template.yml
Deployments are failing because the private key doesn't exist in AWS. Remove retrieval of key for now to get deployments working again. Testing can still be done locally and in GitHub using committed keys.
Added a ticket to store and retrieve keys in deployed envs:
https://govukverify.atlassian.net/browse/ATO-978
=> BAU: Fix deployments by removing retrieval of private key

ipv-stub-template.yml
New encryption key pair has been added in build (in Secrets Manager and Parameter store) under /orch-stubs/ipv-private-encryption-key and /orch-stubs/ipv-public-encryption-key
Will need to configure Orchestration to return this key from `ConfigurationService::getIPVAuthEncryptionPublicKey` in build
IPV_PUBLIC_SIGNING_KEY isn't currently used (the stub doesn't validate the signature) so leaving blank for now
=> ATO-978: Retrieve IPV private encryption key from AWS Secrets Manager

src/main/ipv-stub/ipv-user-identity.ts
Should just be token not whole object
=> BAU: Fix parsing of token in user-identity handler

src/main/ipv-stub/ipv-authorize.ts
Previous way was incorrect implementation
=> BAU: Retrieve JWT from query string parameters rather than header

.github/workflows/deploy-stubs-build-and-promote-auth.yml, .github/workflows/deploy-stubs-build-and-promote-ipv.yml, .github/workflows/deploy-stubs-dev.yml, .github/workflows/deploy-stubs.yml, .github/workflows/pull-request.yml, .github/workflows/run-checks.yml, infrastructure/configuration/build/build-auth-stub-pipeline/parameters.json, infrastructure/configuration/build/build-ipv-stub-pipeline/parameters.json, infrastructure/configuration/dev/dev-auth-stub-pipeline/parameters.json, infrastructure/configuration/dev/dev-ipv-stub-pipeline/parameters.json, infrastructure/provision_all.sh
Since we have split the template files of the stub types (IPV , Auth) we will need to create a workflow and pipeline per stub.
- They should detect changes and only deployed the modified stubs
- The dev pipeline should allow selecting which stub to deploy
=> ATO-939: Setup specific workflows and pipelines for stub type

ipv-stub-template.yml, src/main/ipv-stub/service/dynamodb-form-response-service.ts
- Make it clear that the table is used by IPV stub
- Give it a name in the template to distinguish it from auth code / access token tables
=> BAU: Improve naming of IPV stub user identity table

src/main/ipv-stub/data/ipv-dummy-constants.ts, src/main/ipv-stub/ipv-token.ts, src/main/ipv-stub/ipv-user-identity.ts, src/main/ipv-stub/service/dynamodb-form-response-service.ts
Rather than using a hard-coded access token, instead 
- Generate access token at runtime in ipv-token and save it against user identity. 
- When the token is retrieved in ipv-user-identity, validate the TTL and return null if it is expired. 
- Throw if null is found (either token not in DB or has expired)
=> ATO-1001: Persist access token

package.json
Previously, if the last SAM build happened to finish before the others, npm run build would return before some modules had built. This change continues to build all in parallel, but waits for all three to finish. It also allows the build to be aborted with ctrl+c
=> ATO-871: Fix SAM build race condition

ipv-stub-template.yml, src/main/ipv-stub/helper/env-helper.ts, src/main/ipv-stub/helper/key-helpers.ts, src/main/ipv-stub/ipv-jwks.ts
Add JWKS endpoint to serve the IPV stub public encryption key. The `kid` is created from a hash of the key so it is consistent with a specific key.
Sandpit JWKS:
https://ipvstub.oidc.sandpit.account.gov.uk/.well-known/jwks.json
=> ATO-1272: Add JWKS endpoint for IPV stub public encryption key

src/main/ipv-stub/ipv-jwks.ts
The `alg` value of the encryption key in the stubbed IPV JWKS endpoint is not valid. It should be `RS256`. 
We'd like to filter encryption keys based on their algorithm in https://github.com/govuk-one-login/authentication-api/pull/5942. We need to merge this first else the stubbed environments will fail to encrypt IPV auth requests.
=> ATO-1451: Fix incorrect alg value in JWKS endpoint

src/main/auth-stub/helpers/request-header-helper.test.ts, src/main/auth-stub/helpers/request-header-helper.ts
Adds a RequestHeaderHelper, matching the validation as in https://github.com/govuk-one-login/authentication-api/blob/main/shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java
=> ATP-1545: add request header helper

src/main/auth-stub/interfaces/user-profile-interface.ts, src/main/auth-stub/services/user-profile-dynamodb-service.test.ts, src/main/auth-stub/services/user-profile-dynamodb-service.ts
Defines the UserProfile interface and the service to get UserProfile.
This is currently just a hardcoded object while we build out the MVP. In the future, we plan to build out this service to connect it to a db, such that we can have lots of UserProfiles and enable them to be defined by using the stub, rather than needing to update in code (though we haven't yet scoped that far)
=> ATO-1545: add user profile interface and service

src/main/ipv-stub/ipv-authorize.ts, src/main/ipv-stub/render-ipv-authorize.ts, src/main/template.ts, src/test/integration/ipv-stub/ipv-authorize.test.ts
- Adds the ability to return oAuth errors from the IPV stub 
- Will be used to test the session_invalidated handling as part of this ticket
- Adds a small change to the way the page is rendered under the BAU commit 
- Deployed to dev - have a play with the UI 
- Selected oAuth error from the drop down and entered an error and error_description - was redirected with the values
- Input an oAuth error description and see this is propagated back to Orch
=> ATO-1795: add support for returning oAuth errors from IPV stub

auth-stub-template.yml
Setting up to create a custom domain for the authstub
- created hosted zone with subdomain and export ids of hosted zone and api gateway for manual template.
=> ATO 1581/setup auth stub hosted zone

infrastructure/manual-stacks/auth/dns-zones/README.md, infrastructure/manual-stacks/auth/dns-zones/deploy_dns_zone.sh, infrastructure/manual-stacks/auth/dns-zones/template.yaml
Create custom domain for auth stub
Create stack in orch account for custom domain resources. The hosted zone and linking between auth and orch for the subdomain creation has been done first.
Tested in dev connected to authdev3
=> ATO 1829/create auth stub custom domain name

.github/workflows/deploy-stubs.yml, .github/workflows/run-checks.yml, .npmrc, auth-stub-template.yml, ipv-stub-template.yml, spot-stub-template.yml
Some small changes to the way we pull in dependencies, namely:
- Use `npm ci` not `npm install` in our sam build and GHAs 
- Adds a `.npmrc` with `ignore-scripts=true` to ensure lifecycle scripts are ignored
=> BAU: Improve dependency management

auth-stub-template.yml, infrastructure/manual-stacks/README.md, infrastructure/manual-stacks/auth/dns-zones/README.md, infrastructure/manual-stacks/auth/dns-zones/deploy_dns_zone.sh, infrastructure/manual-stacks/auth/dns-zones/template.yaml, infrastructure/manual-stacks/auth/link-hosted-zone/README.md, infrastructure/manual-stacks/auth/link-hosted-zone/deploy_link_hosted_zone.sh, infrastructure/manual-stacks/auth/link-hosted-zone/template.yaml
Repoints the auth stub to authdev3 as this was pointing to a different domain as part of work to run through an end-to-end journey
=> ATO-1830 move auth stub domain to authdev3
