govuk-one-login/orch-stubs

.github/workflows/deploy-stubs-dev.yml, .github/workflows/deploy-stubs.yml, .github/workflows/pull-request.yml, .github/workflows/run-checks.yml, infrastructure/configuration/dev/README.md, infrastructure/configuration/dev/dev-orch-stubs-pipeline/parameters.json, infrastructure/configuration/dev/tags.json, infrastructure/provision_all.sh
Added infrastructure for dev pipeline - deployed in orchestration-dev account
Added github actions to initialise deployment to dev
added github secrets so github workflows to deploy to dev
=> Ato 875/deploy dev pipeline

.github/workflows/deploy-stubs.yml, auth-stub-template.yml, ipv-stub-template.yml
switched to npm to run build
added permission boundary to template
added signing config to template
=> ATO-875: FIx build and deploy from dev pipeline in GHA

README.md
Update README with required version of AWS SAM CLI
=> BAU: Update README with required version of AWS SAM CLI

ipv-stub-template.yml, package-lock.json, package.json, src/main/ipv-stub/service/dynamodb-form-response-service.ts
Create the infrastructure to be able to get store in dynamoDb
To review - setup config and naming.
=> ATO-864: create dynamoDb infrastructure

package-lock.json, package.json
- Dropping back to node 20 to match lambda runtime - see [here](https://github.com/govuk-one-login/orch-stubs/pull/48#issuecomment-2268626120)
=> BAU: Drop back to node20

package.json, src/main/ipv-stub/ipv-authorize.ts, src/main/ipv-stub/service/dynamodb-form-response-service.ts
=> BAU: Fix linting

src/main/ipv-stub/data/example-user-identity.ts, src/main/ipv-stub/interfaces/user-identity-interface.ts, src/main/ipv-stub/ipv-user-identity.ts, src/test/integration/ipv-stub/data/expected-user-identity.ts, src/test/integration/ipv-stub/ipv-user-identity.test.ts
Simply returning hard coded User Identity for the time being
=> ATO-866: IPV User Identity - Return Hard Coded Identity

src/main/ipv-stub/ipv-token.ts, src/test/integration/ipv-stub/ipv-token.test.ts
Should be 200 not 302 redirect
=> BAU: Fix IPV token handler HTTP code

infrastructure/manual-stacks/dns-zones/README.md, infrastructure/manual-stacks/dns-zones/deploy_dns_zone.sh, infrastructure/manual-stacks/dns-zones/template.yaml, infrastructure/manual-stacks/link-hosted-zone/README.md, infrastructure/manual-stacks/link-hosted-zone/deploy_link_hosted_zone.sh, infrastructure/manual-stacks/link-hosted-zone/template.yaml, ipv-stub-template.yml
Create a custom domain for the ipv orchestration stub
Create hosted zone on Orch account
Create associated NS record in root domain account via manual deployment
Create Certificate, Gateway domain , gateway mapping and A record via manual deployment
=> Ato 1016/create custom domain name for ipv stub

infrastructure/manual-stacks/link-hosted-zone/template.yaml
Add build NS records to deploy into the OIDC hosted zone
=> ATO-1016: add build ns records

src/main/ipv-stub/ipv-authorize.ts
Parse the form data into the userIdentity Object.
The form at the moment includes more information than we use. The credentialJWT is still hardcoded as we do not generate one yet.
=> ATO-1000: parse the form into the user Identity object

src/main/ipv-stub/README.md
Docs to setup sandpit so that the IPV orch stub can be tested using the RP stub
=> BAU: add readme for testing the IPV stub with the RP stub

.github/workflows/deploy-stubs-build-and-promote-auth.yml, .github/workflows/deploy-stubs-build-and-promote-spot.yml, .github/workflows/run-checks.yml, README.md, jest.config.ci.ts, jest.config.ts, package.json, src/main/ipv-stub/utils/user-identity-example-data.ts, src/test/integration/setup.ts
Run the tests in the pipeline and deploy the SPOT stub to build. Best reviewed commit-wise
=> ATO-871: Deploy spot stub

.github/workflows/run-checks.yml
Sonarcloud is being deprecated
=> ATO-1448: Migrate sonarcloud action to sonarqube

auth-stub-template.yml, scripts/init-infra.sh
Create infrastructure for Auth Stub dynamo tables
- AuthCode table
- Token table
Created the associated read and write permissions.
=> ATO 1538: create dynamo stores for auth stub

auth-stub-template.yml
Creating an Auth encryption key for the auth stub:
Key pair created and stored in KMS 
public key in KMS- ` dev-auth-stub-authentication-public-encryption-key`
Tested in Dev
=> ATO-1531: create enccryption and decryption key pair in KMS

src/main/helper/result-helper.ts, src/main/ipv-stub/helper/env-helper.ts, src/main/ipv-stub/helper/key-helpers.ts, src/main/ipv-stub/ipv-authorize.ts, src/main/ipv-stub/ipv-jwks.ts, src/main/ipv-stub/ipv-token.ts, src/main/ipv-stub/ipv-user-identity.ts
Refactor to move helpers out to repo level
=> BAU: move out lambda results helper to repo level for all stubs

src/main/auth-stub/auth-authorize.ts, src/main/auth-stub/auth-userinfo.test.ts, src/main/auth-stub/auth-userinfo.ts, src/main/auth-stub/helpers/request-header-helper.test.ts, src/main/auth-stub/helpers/request-header-helper.ts, src/main/auth-stub/interfaces/user-info-claim-interface.ts, src/main/auth-stub/services/access-token-dynamodb-service.test.ts, src/main/auth-stub/services/user-profile-dynamodb-service.test.ts, src/main/auth-stub/services/user-profile-dynamodb-service.ts, src/main/auth-stub/test-helper/mock-token-data-helper.ts, src/main/auth-stub/test-helper/test-access-token-dynamodb-service.ts, src/main/helper/result-helper.ts, src/test/integration/auth-stub/auth-authorize.test.ts, src/test/integration/auth-stub/auth-userinfo.test.ts
Part of the auth flow for auth-stub. Gets `UserProfile` from SubjectID (which is gotten from the access token) also added auth header validation
=> ATO-1545: Update user info lambda

auth-stub-template.yml, scripts/init-infra.sh
Create AWS dynamoDb table for userProfile and the associated permissions
=> ATO 1547/auth stub user profile table infrastructure

auth-stub-template.yml, src/main/auth-stub/auth-token.test.ts, src/main/auth-stub/auth-token.ts, src/main/auth-stub/helpers/config.ts, src/main/auth-stub/helpers/env-helper.ts, src/main/auth-stub/helpers/token-validation-helper.test.ts, src/main/auth-stub/helpers/token-validation-helper.ts, src/main/auth-stub/test-helper/mock-auth-code-data-helper.ts, src/main/auth-stub/test-helper/test-setup.ts, src/test/integration/auth-stub/auth-token.test.ts, src/test/integration/auth-stub/helpers/test-setup.ts
adds validation for
- AuthCode
- request parameters
- client assertion and signature verification
=> ATO 1544/validation token auth stub

src/main/auth-stub/auth-authorize.test.ts, src/main/auth-stub/auth-authorize.ts, src/main/auth-stub/helpers/mock-token-data-helper.ts, src/main/auth-stub/services/user-profile-dynamodb-service.ts
Add a user at the start of authorize for the authorize and userInfo lambda to use
=> Ato 1706/add temporary user profile

README.md, package.json
Create links to each stub and make it more obvious to follow each specific readme for each stub
=> ATO-1683: update main readme for stubs

ipv-stub-template.yml, src/main/auth-stub/data/auth-dummy-constants.ts, src/main/ipv-stub/config/config.ts, src/main/ipv-stub/data/ipv-dummy-constants.ts, src/test/integration/auth-stub/auth-userinfo.test.ts
Reverts govuk-one-login/orch-stubs#324
=> Revert "ATO-1703: replace sandpit with authdev3"

src/main/auth-stub/README.md
Add readme to give instructions to be able to use RP stub with auth stub
=> ATO-1550: add readme to configure RP stub to use auth stub
